### PR TITLE
ability to use one log file until the size-limit

### PR DESCRIPTION
**Pull request by ostropik**
- added ability to use one log file until the size-limit will be reached (optional for backward compatibility)

### CODE REVIEW

**Comment by ostropik** [comment]
Hello, plz help me recognize "lint" issue. I will be grateful if also fix it

**Comment by ostropik** [comment]
Does need any actions from my side?

**Comment by an-tao** [comment]
> Does need any actions from my side?

I‘m sorry for the delay in merging. It appears that your code style is different from our current style. I will make the necessary modifications to ensure that it aligns with our standards and then merge the pull request. Thank you very much for submitting the patch.

**Comment by an-tao** [comment]
@ostropik In order to be consistent with the code style of this project, I made some modifications. please check it out. thanks.

**Comment by ostropik** [comment]
Logic is a little bit _inversed_ but looks like works as before and properly. review passed

**Pull request merged**
