### PR TITLE
TRNANTOR_LOG_COMPACT - compact logs without source code details(line, file name etc)

### PR DESCRIPTION
**Pull request by ostropik**
- compact logs without source code details(line, file name etc). Preprocessor TRNANTOR_LOG_COMPACT

### CODE REVIEW

**Comment by ostropik** [comment]
Can't see gcc errors(
But before I need to understand, does this idea of COMPACT_LOGGER applicable for framework changes, or i should chose another logging framework?

**Comment by an-tao** [comment]
@ostropik Thanks for your patch, IMHO, I prefer to use output Macros such as LOG_COMPACT_TRACE, LOG_COMPACT_DEBUG, etc.
Using the TRANTOR_LOG_COMPACT macro may lead the ABI problem because it appears both in the public header and the implement file.

**Comment by ostropik** [comment]
LOG_COMPACT_TRACE - we can face conflicts with other frameworks which decide also use some LOG_COMPACT_TRACE. So that is why I proposed to use TRNANTOR_LOG_COMPACT. 

For example:
- build trantor lib with this type of logger (for example RELEASE)
- build our specific solution which will use public headers from different libs
- and for use trantor.lib in mode "compact" into huge of preprocessor defines for **different libraries**
- Example of possible collision : some OpenSSL, or MySuperLib decided use LOG_COMPACT_TRACE  but in fact we don't need this

**Comment by ostropik** [comment]
Ok, agree **LOG_COMPACT** . So how can I understand, we can continue with this change request? 

- I yes, plz advise me line/error with GCC. (i have only MVSC)
- If no...so let me know)

**Comment by an-tao** [comment]
> Ok, agree **LOG_COMPACT** . So how can I understand, we can continue with this change request?
> 
> * I yes, plz advise me line/error with GCC. (i have only MVSC)
> * If no...so let me know)

please use clang-format (v11.0.1) to format your code (run the format.sh script). Or I can help you format the code to pass the CI pipeline.

**Comment by ostropik** [comment]
Plz help me with clang-format (v11.0.1). I have tried MSVC plugin, Visual Studio Code, and online formatter.  Can't found mistake exactly in my changes(

**Comment by an-tao** [comment]
You may have misunderstood my meaning. The specific issue I was referring to is that Trantor can be released as a library. If the macro is not defined when compiling Trantor, but is defined when using the Trantor library, it will inevitably lead to compilation errors as the macro affects both the public header files and the source files. We should avoid this design.

**Comment by ostropik** [comment]
Looks like understood you. Please, check the new variant.

**Comment by ostropik** [comment]
Hello, does it need additional action from my side?

**Pull request merged**
